version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  travels.api:
    container_name: travels-api
    image: ${DOCKER_REGISTRY-}travelsapi
    ports:
      - "5190:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver
    entrypoint: [ "dotnet", "Travels.API.dll" ]
    build:
      context: .
      dockerfile: Server/Travels.API/Dockerfile
    volumes:
      - ./Server/Travels.API/data:/data

  frontend:
    container_name: travels-frontend
    build:
      context: ./Client/Travels.GUI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - travels.api

volumes:
  sqlserverdata:
